grafana:
  enabled: true
  adminPassword: <type your admin password>
  persistence:
    type: pvc
    enabled: true
    existingClaim: <pvc we create for grafana from above>
  path: /var/lib/grafana
  tolerations:
  - <put here if needed>
  nodeSelector:
    <put here if needed>
  grafana.ini:
    paths:
      data: /var/lib/grafana/
      logs: /var/log/grafana
      plugins: /var/lib/grafana/plugins
      provisioning: /etc/grafana/provisioning
    analytics:
      check_for_updates: true
    grafana_net:
      url: https://grafana.net
    log:
      mode: console
    # To make grafana send emails
    smtp:
      enabled: true
      host: smtp.gmail.com:587
      user: <email username>
      password: <email password>
    # To enable login with gmail
    auth.google:
      enabled: true
      client_id: <client_id>
      client_secret: <client_id>
      scopes: https://www.googleapis.com/auth/userinfo.profile https://www.googleapis.com/auth/userinfo.email
      auth_url: https://accounts.google.com/o/oauth2/auth
      token_url: https://accounts.google.com/o/oauth2/token
      allowed_domains: <x.com>
      allow_sign_up: true
    server:
      root_url: <grafana root url>

prometheus:
  enabled: true
  prometheusSpec:
    tolerations:
    - <put here if needed>
    nodeSelector:
      <put here if needed>
    storageSpec:
      volumeClaimTemplate:
        metadata:
          name: prometheus-data
        spec:
          storageClassName: "monitoring-dynamic-efs-sc" # We created at volumes.yaml
          accessModes: ["ReadWriteMany"]
          resources:
            requests:
              storage: 60Gi
  initContainers: 
  retention: 7d
  securityContext:
    runAsGroup: 0
    runAsNonRoot: false
    runAsUser: 0

alertmanager:
  enabled: true 
  alertmanagerSpec:
    tolerations:
    - <put here if needed>
    nodeSelector:
      <put here if needed>
    retention: 168h #7 days
    securityContext:
      runAsNonRoot: false
    storage: 
      volumeClaimTemplate:
        metadata:
          name: alertmanager-data
        spec:
          storageClassName: "monitoring-dynamic-efs-sc" # We created at volumes.yaml
          accessModes: ["ReadWriteMany"]
          resources:
            requests:
              storage: 20Gi
